apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260626-190220-d6jd0f42gh82-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260626-190220-d6jd0f42gh82.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260626-190220-d6jd0f42gh82-service
            port:
              number: 80
